# Default configs

# Redis
REDIS_HOST='localhost'
REDIS_PORT=6379
REDIS_DB=0
REDIS_NAMESPACE='crowdbreaks'
REDIS_LOGSTASH_QUEUE_KEY='logstash'
REDIS_SUBMIT_QUEUE_KEY='es_submit'
REDIS_SENTIMENT_QUEUE_KEY='sentiment'

# num processes
NUM_PROCESSES_PREPROCESSING=2



