FROM python:3
MAINTAINER Martin Müller"martin.muller@epfl.ch"

COPY ./requirements.txt /home/app/requirements.txt
WORKDIR /home/app
RUN pip3 install -r requirements.txt

COPY . /home/app

# create unprivileged user
RUN adduser --disabled-password --gecos '' celery-user

CMD ["gunicorn", "-c", "gunicorn_config.py", "--log-config", "logging.conf", "wsgi:app"]

